FROM golang:latest

MAINTAINER YUKI HORITA <y-horita-42t@eagle.sophia.ac.jp>

WORKDIR /go

ADD . /go

RUN go get "github.com/line/line-bot-sdk-go/linebot" &\\
    go get "github.com/gin-gonic/gin" &\\






