FROM python:3.6


MAINTAINER YUKI HORITA <y-horita-42t@eagle.sophia.ac.jp>

RUN set -x && \
    apt-get -y update && \
    apt-get -y upgrade && \
    apt-get install -y vim && \
    apt-get install -y sudo

WORKDIR /usr/src/rails

VOLUME /usr/src/rails

RUN echo



